services:
  db:
    image: postgres:16
    restart: always
    container_name: yanka_postgres_db
    environment:
      POSTGRES_USER: yanka_user
      POSTGRES_PASSWORD: yanka_password
      POSTGRES_DB: yanka_dev
    ports:
      - "5432:5432"
    volumes:
      - ./database/db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./yanka/Webapp/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: yanka_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://yanka_user:yanka_password@db:5432/yanka_dev
    depends_on:
      - db

  frontend:
    build:
      context: ./yanka/Webapp/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: yanka_frontend
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - backend
